### ISSUE TITLE
Zoekformulier

### ISSUE THREAD

**Issue by KrijnHoetmer** [Stefan-Espant/look-and-feel-corporate-identity#1]
Probeer zoekformulieren altijd meteen in een `<form>` te zetten. Scheelt weer een `<div>` :) (En je krijgt er gratis wat extra functionaliteit van je browser door)

https://github.com/Stefan-Espant/look-and-feel-corporate-identity/blob/9319880ca08aad57830a7bd1ee8c63d136e4b7ac/waarneembaar.html#L54-L63

**Comment by Stefan-Espant** [comment]
Form is removed.
